  server:
    port: 8080
    servlet:
      context-path: /
      session:
        timeout: 21600s
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
  spring:
    datasource:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:commercedb;MODE=MySQL;DB_CLOSE_DELAY=-1
      username: commercedb
      password: 123456
      hikari:
        poolName: pool
    h2:
      console:
        enabled: true
        path: /h2-console
    flyway:
      baselineOnMigrate: true
      validateOnMigrate: false


